DATA: GV_AMOUNT TYPE P DECIMALS 2 VALUE '3456.67',
      GV_CPT TYPE I,
      GV_NAME(12) TYPE C,
      GV_CURRENT_DATE TYPE D,
      GV_CURRENT_TIME TYPE T,
      GC_NUM CONSTANT NUMERIC VALUE '12345678',
      GV_STRING TYPE STRING VALUE 'Votre texte ici'.
      
GV_NAME = SY-UNAME.
GV_CURRENT_DATE = SY-DATUM.
GV_CURRENT_TIME = SY-UZEIT.
