REPORT Z_EXERCICE_ABAP.

TYPES: BEGIN OF GS_MARD,
         MATNR TYPE MARD-MATNR,
         WERKS TYPE MARD-WERKS,
         LABST TYPE MARD-LABST,
       END OF GS_MARD.

TYPES: BEGIN OF GS_MARA,
         MATNR TYPE MARA-MATNR,
         MEINS TYPE MARA-MEINS,
       END OF GS_MARA.

TYPES: BEGIN OF ZSTOCK_S,
         MATNR TYPE MATNR,
         WERKS TYPE WERKS_D,
         LABST TYPE LABST,
         MEINS TYPE MEINS,
       END OF ZSTOCK_S.

DATA: GT_MARD TYPE TABLE OF GS_MARD,
      GT_MARA TYPE TABLE OF GS_MARA,
      GT_STOCK TYPE TABLE OF ZSTOCK_S.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: S_MATNR FOR MARD-MATNR,
                S_WERKS FOR MARD-WERKS.
SELECTION-SCREEN END OF BLOCK B1.

START-OF-SELECTION.

  PERFORM GET_DATA.
  PERFORM COLLECT_DATA.
  PERFORM DISPLAY_DATA.

FORM GET_DATA.
  SELECT * FROM MARD INTO TABLE GT_MARD WHERE MATNR IN S_MATNR AND WERKS IN S_WERKS.
  SELECT * FROM MARA INTO TABLE GT_MARA FOR ALL ENTRIES IN GT_MARD WHERE MATNR = GT_MARD-MATNR.
ENDFORM.

FORM COLLECT_DATA.
  CLEAR GT_STOCK.
  LOOP AT GT_MARD INTO DATA(ls_mard).
    MOVE-CORRESPONDING ls_mard TO GT_STOCK.
    COLLECT GT_STOCK.
  ENDLOOP.
  LOOP AT GT_STOCK INTO DATA(ls_stock).
    SELECT SINGLE MEINS FROM GT_MARA INTO ls_stock-MEINS WHERE MATNR = ls_stock-MATNR.
  ENDLOOP.
ENDFORM.

FORM DISPLAY_DATA.
  LOOP AT GT_STOCK INTO DATA(ls_stock).
    WRITE: / ls_stock-MATNR, ls_stock-WERKS, ls_stock-LABST, ls_stock-MEINS.
  ENDLOOP.
ENDFORM.
