TYPES: BEGIN OF TY_STOCK,
         MATNR TYPE MATNR,
         WERKS TYPE WERKS_D,
         LABST TYPE LABST,
         MEINS TYPE MEINS,
       END OF TY_STOCK.

DATA: GS_STOCK TYPE TY_STOCK.
DATA: GT_STOCK TYPE TABLE OF TY_STOCK.
